package com.speech.vault.type;

import lombok.Getter;

@Getter
public enum MessageKey {
    DTO_NOT_FOUND,

    USER_REGISTERED_SUCCESSFULLY,
    USER_ALREADY_EXIST,
    USER_FETCHED_SUCCESSFULLY,
    USER_DATA_NOT_FOUND,
    AUTHOR_NOT_FOUND,

    SPEECH_FETCHED_SUCCESSFULLY,
    SPEECH_SAVED_SUCCESSFULLY,
    SPEECH_DTO_TITLE_REQUIRED,
    SPEECH_DTO_AUTHOR_REQUIRED,
    SPEECH_DTO_EVENT_DATE_REQUIRED,
    SPEECH_DATA_NOT_FOUND,

}
