spring:
  application:
    name: speech-vault
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/polidraft
      username: root
      password: root
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 50
      minimum-idle: 10
  jpa:
    show-sql: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
          fetch_size: 1000
        ddl-auto: none
        dialect: org.hibernate.dialect.MariaDBDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 80